#!/bin/sh
# Generate html docs from src code comments using edoc
erl -pa ../../bson/ebin/ ../../mongodb/ebin -eval 'edoc:application (mongodb, [{index_columns, 1}, {sort_functions, false}, {preprocess, true}]), init:stop()' -noshell
