#!/bin/sh
# Generate html docs from src code comments using edoc
#
# Note; this requires you to have already run make
#
erl -pa ../deps/bson/ebin ../../mongodb/ebin -eval 'edoc:application (mongodb, [{index_columns, 1}, {sort_functions, false}, {preprocess, true}]), init:stop()' -noshell
