name: Runs Dialyzer

on:
  pull_request:
    branches:
      - master

jobs:
  dialyzer:
    runs-on: ubuntu-24.04
    container:
      image: erlang:24-slim
    steps:
      - uses: actions/checkout@v4
      - name: Cache PLTs
        id: cache-plts
        uses: actions/cache@v4
        with:
          path: ~/.cache/rebar3/
          key: ${{ runner.os }}-erlang-${{ hashFiles(format('{0}{1}', github.workspace, '/rebar.lock')) }}
      - run: apt-get update && apt-get --yes install git
      - run: ./rebar3 dialyzer
